version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: utamv
      POSTGRES_USER: utamv
      POSTGRES_DB: utamv
    ports:
      - "5432:5432"
